syntax = "proto3";
package tokad;

message Stub {
  bytes id = 1;
  uint32 port = 2;
}

message Ping {
  Stub source = 1;
}
message Pong {
  Stub source = 1;
}

message Store {
  Stub source = 1;
  bytes key = 2;
  bytes value = 3;
}

message StoreRequest {
  Stub source = 1;
  bytes key = 2;
  bytes value = 3;
  bool publish = 4;
  uint64 publish_time = 5;
}

message Key {
  Stub source = 1;
  bytes key = 2;
}

message Node {
  bytes id = 1;
  string ip = 2;
  uint32 port = 3;
}

message Nodes {
  Stub source = 1;
  repeated Node nodes = 2;
}

message StoreOrNodes {
  oneof oneof {
    Nodes nodes = 1;
    Store store = 2;
  }
}

service Tokad {
  rpc ping(Ping) returns (Pong);
  rpc store(StoreRequest) returns (Pong);
  rpc find_node(Key) returns (Nodes);
  rpc find_value(Key) returns (StoreOrNodes);
}

